name: cashflowx
description: "New Personal Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: any

  # 🔧 Rango compatible con Flutter que fija intl 0.19.x y con el que permite 0.20.x
  intl: ">=0.19.0 <0.21.0"

  shared_preferences: ^2.2.2
  http: ^1.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/l10n/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
